// <auto-generated />
using System;
using APUS.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APUS.Server.Migrations
{
    [DbContext(typeof(ActivityDbContext))]
    [Migration("20250511135850_AvgPaceTypeChanged2")]
    partial class AvgPaceTypeChanged2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APUS.Server.Models.MainActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActivityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AvgHeartRate")
                        .HasColumnType("int");

                    b.Property<int?>("Calories")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MainActivities", "Activities");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("APUS.Server.Models.Bouldering", b =>
                {
                    b.HasBaseType("APUS.Server.Models.MainActivity");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int");

                    b.ToTable("Bouldering", "Activities");
                });

            modelBuilder.Entity("APUS.Server.Models.GpsRelatedActivity", b =>
                {
                    b.HasBaseType("APUS.Server.Models.MainActivity");

                    b.Property<double?>("AvgPace")
                        .HasColumnType("float");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalAscentMeters")
                        .HasColumnType("float");

                    b.Property<double?>("TotalDescentMeters")
                        .HasColumnType("float");

                    b.Property<double?>("TotalDistanceKm")
                        .HasColumnType("float");

                    b.ToTable("GpsRelatedActivities", "Activities");
                });

            modelBuilder.Entity("APUS.Server.Models.Hiking", b =>
                {
                    b.HasBaseType("APUS.Server.Models.GpsRelatedActivity");

                    b.ToTable("Hiking", "Activities");
                });

            modelBuilder.Entity("APUS.Server.Models.Running", b =>
                {
                    b.HasBaseType("APUS.Server.Models.GpsRelatedActivity");

                    b.ToTable("Running", "Activities");
                });

            modelBuilder.Entity("APUS.Server.Models.Bouldering", b =>
                {
                    b.HasOne("APUS.Server.Models.MainActivity", null)
                        .WithOne()
                        .HasForeignKey("APUS.Server.Models.Bouldering", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APUS.Server.Models.GpsRelatedActivity", b =>
                {
                    b.HasOne("APUS.Server.Models.MainActivity", null)
                        .WithOne()
                        .HasForeignKey("APUS.Server.Models.GpsRelatedActivity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APUS.Server.Models.Hiking", b =>
                {
                    b.HasOne("APUS.Server.Models.GpsRelatedActivity", null)
                        .WithOne()
                        .HasForeignKey("APUS.Server.Models.Hiking", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APUS.Server.Models.Running", b =>
                {
                    b.HasOne("APUS.Server.Models.GpsRelatedActivity", null)
                        .WithOne()
                        .HasForeignKey("APUS.Server.Models.Running", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
