// <auto-generated />
using System;
using APUS.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APUS.Server.Migrations
{
    [DbContext(typeof(ActivityDbContext))]
    partial class ActivityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APUS.Server.Models.Activities.MainActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasDiscriminator<string>("ActivityType").HasValue("Activity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("APUS.Server.Models.Activities.Bouldering", b =>
                {
                    b.HasBaseType("APUS.Server.Models.Activities.MainActivity");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("RedPoint")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Bouldering");
                });

            modelBuilder.Entity("APUS.Server.Models.Activities.Running", b =>
                {
                    b.HasBaseType("APUS.Server.Models.Activities.MainActivity");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<int>("Pace")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Running");
                });
#pragma warning restore 612, 618
        }
    }
}
